/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/ // app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientProvider from "./ClientProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Edmich Autoplux",
  description:
    "Nigeria’s trusted B2B auto parts marketplace—Autoplux Market, Mechanics, and Logistics in one platform.",
  keywords: [
    "auto parts",
    "Nigeria",
    "suppliers",
    "mechanics",
    "B2B",
    "Edmich",
  ],
  icons: { icon: "/favicon.ico" },
  openGraph: {
    title: "Edmich Autoplux",
    description:
      "Buy genuine spare parts, connect mechanics, streamline logistics—built for Nigeria and Africa.",
    url: "https://www.edmich.com",
    siteName: "Edmich Autoplux",
    images: [{ url: "/edmich-logo.png", width: 1200, height: 630 }],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Edmich Autoplux",
    description: "Nigeria’s B2B auto parts marketplace.",
    images: ["/edmich-logo.png"],
  },
  metadataBase: new URL("https://www.edmich.com"),
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-neutral-50 text-neutral-900`}>
        {/* ONLY ONE CartProvider */}
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
